# Concatenating Tables

In [1]:
import pandas as pd

In [2]:
EPL = pd.read_excel("./data/EPL.xlsx", sheet_name='EPL')
teamInfo = pd.read_excel("./data/EPL.xlsx", sheet_name='teamInfo') 
games = pd.read_excel("./data/EPL.xlsx", sheet_name='games')
results = pd.read_excel("./data/EPL.xlsx", sheet_name='results', header=None)

We can horizontally concatenate two DataFrames, if they have the same number of observations but do not share any variable names.

In [3]:
season = pd.concat([teamInfo, games], axis=1)
season

,Team,Payroll_M__,Manager,ManagerHireDate,ManagerNationality,Wins,Draws,Losses
0,Leicester City,48.2,Claudio Ranieri,07/13/2015,Italy,23,12,3
1,Arsenal,192.0,Arsène Wenger,1996-01-10 00:00:00,France,20,11,7
2,Tottenham Hotspur,110.5,Mauricio Pochettino,05/27/2014,Argentina,19,13,6
3,Manchester City,193.8,Manuel Pellegrini,06/14/2013,Chile,19,9,10
4,Manchester United,203.0,Louis van Gaal,07/14/2014,Netherlands,19,9,10
5,Southampton,59.5,Ronald Koeman,06/16/2014,Netherlands,18,9,11
6,West Ham United,69.5,Slaven Bilić,2015-09-06 00:00:00,Croatia,16,14,8
7,Liverpool,152.0,Jürgen Klopp,2015-08-10 00:00:00,Germany,16,12,10
8,Stoke City,72.3,Mark Hughes,05/30/2013,Wales,14,9,15
9,Chelsea,215.6,Guus Hiddink,12/19/2015,Netherlands,12,14,12
10,Everton,74.7,David Unsworth,2016-12-05 00:00:00,England,11,14,13
11,Swansea City,51.0,Francesco Guidolin,01/18/2016,Italy,12,11,15
12,Watford,29.0,Quique Sánchez Flores,2015-05-06 00:00:00,Spain,12,9,17
13,West Bromwich Albion,68.5,Tony Pulis,2015-01-01 00:00:00,Wales,10,13,15
14,Crystal Palace,54.3,Alan Pardew,2015-02-01 00:00:00,England,11,9,18
15,Bournemouth,25.0,Eddie Howe,2012-12-10 00:00:00,England,11,9,18
16,Sunderland,71.0,Sam Allardyce,2015-09-10 00:00:00,England,9,12,17
17,Newcastle United,75.8,Rafael Benítez,2016-11-03 00:00:00,Spain,9,10,19
18,Norwich City,37.0,Alex Neil,2015-09-01 00:00:00,Scotland,9,7,22
19,Aston Villa,65.1,Eric Black,03/29/2016,Scotland,3,8,27

Points and goal difference are stored in the results variable, which doesn't have column names. We can assign new column names with the [columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html#pandas-dataframe-columns) property. Now we can concatenate it with season.

In [4]:
results.columns = ["Points", "GoalDifference"]
season = pd.concat([season, results], axis=1)
season

,Team,Payroll_M__,Manager,ManagerHireDate,ManagerNationality,Wins,Draws,Losses,Points,GoalDifference
0,Leicester City,48.2,Claudio Ranieri,07/13/2015,Italy,23,12,3,81,32
1,Arsenal,192.0,Arsène Wenger,1996-01-10 00:00:00,France,20,11,7,71,29
2,Tottenham Hotspur,110.5,Mauricio Pochettino,05/27/2014,Argentina,19,13,6,70,34
3,Manchester City,193.8,Manuel Pellegrini,06/14/2013,Chile,19,9,10,66,30
4,Manchester United,203.0,Louis van Gaal,07/14/2014,Netherlands,19,9,10,66,14
5,Southampton,59.5,Ronald Koeman,06/16/2014,Netherlands,18,9,11,63,18
6,West Ham United,69.5,Slaven Bilić,2015-09-06 00:00:00,Croatia,16,14,8,62,14
7,Liverpool,152.0,Jürgen Klopp,2015-08-10 00:00:00,Germany,16,12,10,60,13
8,Stoke City,72.3,Mark Hughes,05/30/2013,Wales,14,9,15,51,-14
9,Chelsea,215.6,Guus Hiddink,12/19/2015,Netherlands,12,14,12,50,6
10,Everton,74.7,David Unsworth,2016-12-05 00:00:00,England,11,14,13,47,4
11,Swansea City,51.0,Francesco Guidolin,01/18/2016,Italy,12,11,15,47,-10
12,Watford,29.0,Quique Sánchez Flores,2015-05-06 00:00:00,Spain,12,9,17,45,-10
13,West Bromwich Albion,68.5,Tony Pulis,2015-01-01 00:00:00,Wales,10,13,15,43,-14
14,Crystal Palace,54.3,Alan Pardew,2015-02-01 00:00:00,England,11,9,18,42,-12
15,Bournemouth,25.0,Eddie Howe,2012-12-10 00:00:00,England,11,9,18,42,-22
16,Sunderland,71.0,Sam Allardyce,2015-09-10 00:00:00,England,9,12,17,39,-14
17,Newcastle United,75.8,Rafael Benítez,2016-11-03 00:00:00,Spain,9,10,19,37,-21
18,Norwich City,37.0,Alex Neil,2015-09-01 00:00:00,Scotland,9,7,22,34,-28
19,Aston Villa,65.1,Eric Black,03/29/2016,Scotland,3,8,27,17,-49