# Temperatures in Natick, MA

In [17]:
import pandas as pd

In [18]:
temperature_data = pd.read_csv("./data/natickData.csv", header=None)
temperature_data

    0   1   2   3   4   5   6   7   8   9   10  11
0    9  19  37  42  53  67  74  75  62  52  42  34
1    9  18  36  41  53  67  74  74  61  51  42  33
2    8  16  36  41  52  66  73  73  60  49  41  32
3    9  17  35  40  53  66  74  74  59  50  42  32
4   10  18  36  40  55  67  74  75  60  50  43  33
5   10  18  37  41  56  69  76  75  61  51  43  33
6   11  19  37  42  58  69  76  76  62  53  44  33
7   11  19  39  44  59  70  77  77  63  54  44  34
8   13  21  40  46  59  70  78  77  63  56  45  36
9   15  22  41  47  60  72  79  78  64  57  47  36
10  16  23  41  48  62  73  80  79  64  57  47  37
11  19  27  42  51  63  74  82  79  64  57  48  39
12  22  30  45  52  63  74  82  80  66  60  49  40
13  25  33  47  53  64  76  83  81  67  62  49  40
14  27  35  47  53  66  76  83  81  68  62  50  41
15  27  36  46  55  66  75  82  82  68  63  52  40
16  26  34  44  56  67  73  81  82  70  63  53  38
17  22  32  41  55  64  71  79  80  71  62  52  35
18  21  30  40  54  61  70  77  77  70  60  52  33
19  19  29  38  52  59  68  76  76  69  58  50  31
20  17  29  38  50  57  68  74  76  67  58  48  30
21  17  27  37  50  56  67  74  75  65  57  46  29
22  15  23  36  49  53  66  73  75  65  56  45  28
23  14  22  34  48  50  66  73  75  64  56  42  28

temperature-data is a matrix with the average hourly Fahrenheit temperature in Natick, Massachusetts, home of MathWorks, where each row represents the hour of the day and each column represents the month.

In [19]:
temperature_standard_deviation = temperature_data.std()
temperature_standard_deviation

0     6.204253
1     6.415420
2     3.888854
3     5.380453
4     4.973663
5     3.375101
6     3.517039
7     2.713359
8     3.457558
9     4.402733
10    3.776357
11    3.887690
dtype: float64

In [20]:
max_standard_deviation = temperature_standard_deviation.max()
max_standard_deviation

6.415419604020626

In [21]:
temperature_range = temperature_data.max() - temperature_data.min()
temperature_range

0     19
1     20
2     13
3     16
4     17
5     10
6     10
7      9
8     12
9     14
10    12
11    13
dtype: int64

In [22]:
temperature_range.max()

20

In [23]:
temperature_range.min()

9